// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DailyStat struct {
	UserID        string      `json:"user_id"`
	StatDate      pgtype.Date `json:"stat_date"`
	ActivityCount int32       `json:"activity_count"`
}

type Note struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type NoteLink struct {
	ID           pgtype.UUID        `json:"id"`
	SourceNoteID pgtype.UUID        `json:"source_note_id"`
	TargetNoteID pgtype.UUID        `json:"target_note_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Color       string             `json:"color"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID          string             `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   string             `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
