// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectNote = `-- name: CreateProjectNote :one
INSERT INTO notes (user_id, project_id, title, content)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, project_id, title, content, created_at, updated_at, deleted_at
`

type CreateProjectNoteParams struct {
	UserID    string      `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
}

func (q *Queries) CreateProjectNote(ctx context.Context, arg CreateProjectNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createProjectNote,
		arg.UserID,
		arg.ProjectID,
		arg.Title,
		arg.Content,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createQuicknote = `-- name: CreateQuicknote :one
INSERT INTO notes (user_id, project_id, title, content)
VALUES ($1, NULL, $2, $3)
RETURNING id, user_id, project_id, title, content, created_at, updated_at, deleted_at
`

type CreateQuicknoteParams struct {
	UserID  string `json:"user_id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

func (q *Queries) CreateQuicknote(ctx context.Context, arg CreateQuicknoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createQuicknote, arg.UserID, arg.Title, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteNoteLinksByNoteID = `-- name: DeleteNoteLinksByNoteID :exec
DELETE FROM note_links
WHERE source_note_id = $1 OR target_note_id = $1
`

func (q *Queries) DeleteNoteLinksByNoteID(ctx context.Context, sourceNoteID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNoteLinksByNoteID, sourceNoteID)
	return err
}

const getLinkedNotes = `-- name: GetLinkedNotes :many
SELECT n.id, n.user_id, n.project_id, n.title, n.content, n.created_at, n.updated_at, n.deleted_at FROM notes n
INNER JOIN note_links nl ON n.id = nl.target_note_id
WHERE nl.source_note_id = $1 AND n.deleted_at IS NULL
ORDER BY n.created_at DESC
`

func (q *Queries) GetLinkedNotes(ctx context.Context, sourceNoteID pgtype.UUID) ([]Note, error) {
	rows, err := q.db.Query(ctx, getLinkedNotes, sourceNoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkedNotesByNoteID = `-- name: GetLinkedNotesByNoteID :many
SELECT DISTINCT n.id, n.user_id, n.project_id, n.title, n.content, n.created_at, n.updated_at, n.deleted_at FROM notes n
INNER JOIN note_links nl ON (n.id = nl.target_note_id AND nl.source_note_id = $1)
                         OR (n.id = nl.source_note_id AND nl.target_note_id = $1)
WHERE n.deleted_at IS NULL
ORDER BY n.created_at DESC
`

func (q *Queries) GetLinkedNotesByNoteID(ctx context.Context, sourceNoteID pgtype.UUID) ([]Note, error) {
	rows, err := q.db.Query(ctx, getLinkedNotesByNoteID, sourceNoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, user_id, project_id, title, content, created_at, updated_at, deleted_at FROM notes
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetNoteByID(ctx context.Context, id pgtype.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNoteByIDAndUser = `-- name: GetNoteByIDAndUser :one
SELECT id, user_id, project_id, title, content, created_at, updated_at, deleted_at FROM notes
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetNoteByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetNoteByIDAndUser(ctx context.Context, arg GetNoteByIDAndUserParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByIDAndUser, arg.ID, arg.UserID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteNote = `-- name: HardDeleteNote :exec
DELETE FROM notes
WHERE id = $1 AND user_id = $2
`

type HardDeleteNoteParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) HardDeleteNote(ctx context.Context, arg HardDeleteNoteParams) error {
	_, err := q.db.Exec(ctx, hardDeleteNote, arg.ID, arg.UserID)
	return err
}

const insertNoteLink = `-- name: InsertNoteLink :one
INSERT INTO note_links (source_note_id, target_note_id)
VALUES ($1, $2)
ON CONFLICT (source_note_id, target_note_id) DO UPDATE
SET created_at = note_links.created_at
RETURNING id, source_note_id, target_note_id, created_at
`

type InsertNoteLinkParams struct {
	SourceNoteID pgtype.UUID `json:"source_note_id"`
	TargetNoteID pgtype.UUID `json:"target_note_id"`
}

func (q *Queries) InsertNoteLink(ctx context.Context, arg InsertNoteLinkParams) (NoteLink, error) {
	row := q.db.QueryRow(ctx, insertNoteLink, arg.SourceNoteID, arg.TargetNoteID)
	var i NoteLink
	err := row.Scan(
		&i.ID,
		&i.SourceNoteID,
		&i.TargetNoteID,
		&i.CreatedAt,
	)
	return i, err
}

const listDeletedNotesByUser = `-- name: ListDeletedNotesByUser :many
SELECT id, user_id, project_id, title, content, created_at, updated_at, deleted_at FROM notes
WHERE user_id = $1 AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

func (q *Queries) ListDeletedNotesByUser(ctx context.Context, userID string) ([]Note, error) {
	rows, err := q.db.Query(ctx, listDeletedNotesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesByProject = `-- name: ListNotesByProject :many
SELECT id, user_id, project_id, title, content, created_at, updated_at, deleted_at FROM notes
WHERE user_id = $1 AND project_id = $2 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListNotesByProjectParams struct {
	UserID    string      `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) ListNotesByProject(ctx context.Context, arg ListNotesByProjectParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesByProject, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuicknotes = `-- name: ListQuicknotes :many
SELECT id, user_id, project_id, title, content, created_at, updated_at, deleted_at FROM notes
WHERE user_id = $1 AND project_id IS NULL AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListQuicknotes(ctx context.Context, userID string) ([]Note, error) {
	rows, err := q.db.Query(ctx, listQuicknotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreNote = `-- name: RestoreNote :one
UPDATE notes
SET deleted_at = NULL,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NOT NULL
RETURNING id, user_id, project_id, title, content, created_at, updated_at, deleted_at
`

type RestoreNoteParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) RestoreNote(ctx context.Context, arg RestoreNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, restoreNote, arg.ID, arg.UserID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteNote = `-- name: SoftDeleteNote :exec
UPDATE notes
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteNoteParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) SoftDeleteNote(ctx context.Context, arg SoftDeleteNoteParams) error {
	_, err := q.db.Exec(ctx, softDeleteNote, arg.ID, arg.UserID)
	return err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET title = $3,
    content = $4,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, project_id, title, content, created_at, updated_at, deleted_at
`

type UpdateNoteParams struct {
	ID      pgtype.UUID `json:"id"`
	UserID  string      `json:"user_id"`
	Title   string      `json:"title"`
	Content string      `json:"content"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Content,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
