// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectsByUser = `-- name: CountProjectsByUser :one
SELECT COUNT(*) FROM projects
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountProjectsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, title, description, color, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, title, description, color, status, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	UserID      string `json:"user_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Color       string `json:"color"`
	Status      string `json:"status"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Color,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Color,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, user_id, title, description, color, status, created_at, updated_at, deleted_at FROM projects
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Color,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByIDAndUser = `-- name: GetProjectByIDAndUser :one
SELECT id, user_id, title, description, color, status, created_at, updated_at, deleted_at FROM projects
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetProjectByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetProjectByIDAndUser(ctx context.Context, arg GetProjectByIDAndUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIDAndUser, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Color,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT id, user_id, title, description, color, status, created_at, updated_at, deleted_at FROM projects
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListProjectsByUser(ctx context.Context, arg ListProjectsByUserParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Color,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteProjectParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) error {
	_, err := q.db.Exec(ctx, softDeleteProject, arg.ID, arg.UserID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET title = $3,
    description = $4,
    color = $5,
    status = $6,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, title, description, color, status, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      string      `json:"user_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Color       string      `json:"color"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Color,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Color,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
