// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountProjectsByUser(ctx context.Context, userID string) (int64, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectNote(ctx context.Context, arg CreateProjectNoteParams) (Note, error)
	CreateQuicknote(ctx context.Context, arg CreateQuicknoteParams) (Note, error)
	DeleteNoteLinksByNoteID(ctx context.Context, sourceNoteID pgtype.UUID) error
	GetDailyStatsByYear(ctx context.Context, arg GetDailyStatsByYearParams) ([]DailyStat, error)
	GetLinkedNotes(ctx context.Context, sourceNoteID pgtype.UUID) ([]Note, error)
	GetLinkedNotesByNoteID(ctx context.Context, sourceNoteID pgtype.UUID) ([]Note, error)
	GetNoteByID(ctx context.Context, id pgtype.UUID) (Note, error)
	GetNoteByIDAndUser(ctx context.Context, arg GetNoteByIDAndUserParams) (Note, error)
	GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProjectByIDAndUser(ctx context.Context, arg GetProjectByIDAndUserParams) (Project, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	HardDeleteNote(ctx context.Context, arg HardDeleteNoteParams) error
	HardDeleteProject(ctx context.Context, arg HardDeleteProjectParams) error
	IncrementDailyStat(ctx context.Context, arg IncrementDailyStatParams) (DailyStat, error)
	InsertNoteLink(ctx context.Context, arg InsertNoteLinkParams) (NoteLink, error)
	ListDeletedNotesByUser(ctx context.Context, userID string) ([]Note, error)
	ListDeletedProjectsByUser(ctx context.Context, userID string) ([]Project, error)
	ListNotesByProject(ctx context.Context, arg ListNotesByProjectParams) ([]Note, error)
	ListProjectsByUser(ctx context.Context, arg ListProjectsByUserParams) ([]Project, error)
	ListQuicknotes(ctx context.Context, userID string) ([]Note, error)
	RestoreNote(ctx context.Context, arg RestoreNoteParams) (Note, error)
	RestoreProject(ctx context.Context, arg RestoreProjectParams) (Project, error)
	SoftDeleteNote(ctx context.Context, arg SoftDeleteNoteParams) error
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) error
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
