// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyStatsByYear = `-- name: GetDailyStatsByYear :many
SELECT user_id, stat_date, activity_count FROM daily_stats
WHERE user_id = $1 AND EXTRACT(YEAR FROM stat_date)::int = $2::int
ORDER BY stat_date ASC
`

type GetDailyStatsByYearParams struct {
	UserID string `json:"user_id"`
	Year   int32  `json:"year"`
}

func (q *Queries) GetDailyStatsByYear(ctx context.Context, arg GetDailyStatsByYearParams) ([]DailyStat, error) {
	rows, err := q.db.Query(ctx, getDailyStatsByYear, arg.UserID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyStat{}
	for rows.Next() {
		var i DailyStat
		if err := rows.Scan(&i.UserID, &i.StatDate, &i.ActivityCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementDailyStat = `-- name: IncrementDailyStat :one
INSERT INTO daily_stats (user_id, stat_date, activity_count)
VALUES ($1, $2, 1)
ON CONFLICT (user_id, stat_date)
DO UPDATE SET activity_count = daily_stats.activity_count + 1
RETURNING user_id, stat_date, activity_count
`

type IncrementDailyStatParams struct {
	UserID   string      `json:"user_id"`
	StatDate pgtype.Date `json:"stat_date"`
}

func (q *Queries) IncrementDailyStat(ctx context.Context, arg IncrementDailyStatParams) (DailyStat, error) {
	row := q.db.QueryRow(ctx, incrementDailyStat, arg.UserID, arg.StatDate)
	var i DailyStat
	err := row.Scan(&i.UserID, &i.StatDate, &i.ActivityCount)
	return i, err
}
